# Etapa de build
FROM jelastic/maven:3.9.4-openjdk-21.ea-b17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src

RUN mvn clean install -DskipTests

# Etapa para rodar a aplicação
FROM openjdk:21-jdk
WORKDIR /app
# Copia o JAR do diretório target, onde o Maven gera o build
COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
