# Etapa de build
FROM ubuntu:latest AS build
RUN apt-get update
RUN apt-get install openjdk-21-jdk maven -y
COPY . /app
WORKDIR /app
RUN mvn clean install

# Etapa para rodar a aplicação
FROM openjdk:21-jdk-slim
EXPOSE 8080
COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
